author: "Joseph Salmon, Benjamin Charlier, Nicolas Meyer, Benoîte de Saporta"
lang: fr
project:
  type: website
  render:
    - index.qmd
    - Courses/notations.qmd
    - Courses/th_asymptotique.qmd
    - Courses/simulation.qmd

website:
  title: "HAX603X: Modélisation stochastique"
  site-url: https://josephsalmon.github.io/HAX603X/
  repo-url: https://github.com/josephsalmon/HAX603X
  page-navigation: true
  repo-actions: [source, issue]
  navbar:
    title: HAX603X
    background: primary
    search: true
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Courses"
        menu:
          - Courses/notations.qmd
          - Courses/th_asymptotique.qmd
          - Courses/simulation.qmd
      - text: "TD"
      - text: "Bonus"

    tools:
      - icon: github
        href: https://github.com/josephsalmon/HAX603X
        text: GitHub
      - icon: bicycle
        href: https://moodle.umontpellier.fr/course/view.php?id=25763
        text: Moodle

format:
  html:
    theme:
      spacelab
      # light: spacelab
    css: custom.scss
    # mainfont: Atkinson Hyperlegible
    html-math-method: katex
    toc-location: left
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools:
      toggle: false
      source: false
    code-overflow: wrap
    highlight-style: github
    fig-responsive: true
    fig.align: center
    reference-location: margin
    citation-location: margin
    # self-contained: true
    # fig-format: svg
